/* Com_Cfg.h */
#ifndef TOPPERS_A_COM_CFG_H
#define TOPPERS_A_COM_CFG_H

#define COM_DEV_ERROR_DETECT STD_ON
#define COM_ENABLE_MDT_FOR_CYCLIC_TRANSMISSION STD_ON
#define COM_RETRY_FAILED_TRANSMIT_REQUESTS STD_OFF
#define COM_VERSION_INFO_API STD_ON
#define COM_IPDU_CANCELLATION_SUPPORT STD_ON
#define COM_SUPPORTED_IPDU_GROUPS 1U

/* [ecuc_sws_2108] */
#define ComConf_ComSignal_ComSignal_0 0U
#define ComConf_ComSignal_ComSignal_1 1U
#define ComConf_ComSignal_ComSignal_2 2U
#define ComConf_ComSignal_ComSignal_3 3U
#define ComConf_ComSignal_ComSignal_4 4U
#define ComConf_ComSignal_ComSignal_5 5U
#define ComConf_ComSignal_ComSignal_6 6U
#define ComConf_ComSignal_ComSignal_7 7U
#define ComConf_ComSignal_ComSignal_8 8U
#define ComConf_ComSignal_ComSignal_9 9U
#define ComConf_ComSignal_ComSignal_10 10U
#define ComConf_ComSignal_ComSignal_11 11U
#define ComConf_ComSignal_ComSignal_12 12U
#define ComConf_ComSignal_ComSignal_13 13U
#define ComConf_ComSignal_ComSignal_14 14U
#define ComConf_ComSignal_ComSignal_15 15U
#define ComConf_ComSignal_ComSignal_16 16U
#define ComConf_ComSignal_ComSignal_17 17U
#define ComConf_ComSignal_ComSignal_18 18U
#define ComConf_ComSignal_ComSignal_19 19U
#define ComConf_ComSignal_ComSignal_20 20U
#define ComConf_ComSignal_ComSignal_21 21U
#define ComConf_ComSignal_ComSignal_22 22U
#define ComConf_ComSignal_ComSignal_23 23U
#define ComConf_ComSignal_ComSignal_24 24U
#define ComConf_ComSignal_ComSignal_25 25U
#define ComConf_ComSignal_ComSignal_26 26U
#define ComConf_ComSignal_ComSignal_27 27U
#define ComConf_ComSignal_ComSignal_28 28U
#define ComConf_ComSignal_ComSignal_29 29U
#define ComConf_ComSignal_ComSignal_30 30U
#define ComConf_ComSignal_ComSignal_31 31U
#define ComConf_ComSignal_ComSignal_32 32U
#define ComConf_ComSignal_ComSignal_33 33U
#define ComConf_ComSignal_ComSignal_34 34U
#define ComConf_ComSignal_ComSignal_35 35U
#define ComConf_ComSignal_ComSignal_36 36U
#define ComConf_ComSignal_ComSignal_37 37U
#define ComConf_ComSignal_ComSignal_38 38U
#define ComConf_ComSignal_ComSignal_39 39U
#define ComConf_ComSignal_ComSignal_40 40U
#define ComConf_ComSignal_ComSignal_41 41U
#define ComConf_ComSignal_ComSignal_42 42U
#define ComConf_ComSignal_ComSignal_43 43U
#define ComConf_ComSignal_ComSignal_44 44U
#define ComConf_ComSignal_ComSignal_45 45U
#define ComConf_ComSignal_ComSignal_46 46U
#define ComConf_ComSignal_ComSignal_47 47U
#define ComConf_ComSignal_ComSignal_48 48U
#define ComConf_ComSignal_ComSignal_49 49U
#define ComConf_ComSignal_ComSignal_50 50U
#define ComConf_ComSignal_ComSignal_51 51U
#define ComConf_ComSignal_ComSignal_52 52U
#define ComConf_ComSignal_ComSignal_53 53U
#define ComConf_ComSignal_ComSignal_54 54U
#define ComConf_ComSignal_ComSignal_55 55U
#define ComConf_ComSignal_ComSignal_56 56U
#define ComConf_ComSignal_ComSignal_57 57U
#define ComConf_ComSignal_ComSignal_58 58U
#define ComConf_ComSignal_ComSignal_59 59U
#define ComConf_ComSignal_ComSignal_60 60U
#define ComConf_ComSignal_ComSignal_61 61U
#define ComConf_ComSignal_ComSignal_62 62U
#define ComConf_ComSignal_ComSignal_63 63U
#define ComConf_ComSignal_ComSignal_64 64U
#define ComConf_ComSignal_ComSignal_65 74U
#define ComConf_ComSignal_ComSignal_66 66U
#define ComConf_ComSignal_ComSignal_67 67U
#define ComConf_ComSignal_ComSignal_68 68U
#define ComConf_ComSignal_ComSignal_69 69U
#define ComConf_ComSignal_ComSignal_70 70U
#define ComConf_ComSignal_ComSignal_71 71U
#define ComConf_ComSignal_ComSignal_72 72U
#define ComConf_ComSignal_ComSignal_73 73U
#define ComConf_ComSignal_ComSignal_74 65U
#define ComConf_ComSignal_ComSignal_75 75U
#define ComConf_ComSignal_ComSignal_76 76U
#define ComConf_ComSignal_ComSignal_77 77U
#define ComConf_ComSignal_ComSignal_78 78U
#define ComConf_ComSignal_ComSignal_79 79U
#define ComConf_ComSignal_ComSignal_80 80U
#define ComConf_ComSignal_ComSignal_81 81U
#define ComConf_ComSignal_ComSignal_82 82U
#define ComConf_ComSignal_ComSignal_83 83U

#define ComConf_ComIPdu_ComIPdu_0 0U
#define ComConf_ComIPdu_ComIPdu_1 1U
#define ComConf_ComIPdu_ComIPdu_2 2U
#define ComConf_ComIPdu_ComIPdu_3 3U
#define ComConf_ComIPdu_ComIPdu_4 4U
#define ComConf_ComIPdu_ComIPdu_5 5U
#define ComConf_ComIPdu_ComIPdu_6 6U
#define ComConf_ComIPdu_ComIPdu_7 7U
#define ComConf_ComIPdu_ComIPdu_8 8U
#define ComConf_ComIPdu_ComIPdu_9 9U
#define ComConf_ComIPdu_ComIPdu_10 10U
#define ComConf_ComIPdu_ComIPdu_11 11U

#define ComConf_ComIPduGroup_ComIPduGroup_0 0U

#endif /* TOPPERS_A_COM_CFG_H */

